#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

api_current_rates:
    path: /api/rates/current
    controller: App\Controller\CurrencyController::getCurrentRates
    methods: [GET]

api_historical_rates:
    path: /api/rates/historical
    controller: App\Controller\CurrencyController::getHistoricalRates
    methods: [GET]

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

